# Generated by Django 6.0.5 on 2026-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_agency', '0002_contactlead_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
