# Generated by Django 6.0.5 on 2026-05-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_agency', '0003_contactlead_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome class e.g., 'fa-solid fa-briefcase'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tech', 'Technology'), ('Creative', 'Creative & Marketing')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome class e.g., 'fa-solid fa-code'", max_length=100)),
            ],
        ),
    ]
