# Generated by Django 6.0.5 on 2026-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_agency', '0004_portfolioproject_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_role', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('prev_company', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_role', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioProject',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='contactlead',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactlead',
            old_name='project_details',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactlead',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='contactlead',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactlead',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
