# Generated by Django 6.0.5 on 2026-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_agency', '0005_jobapplication_delete_portfolioproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Senior Backend Architect', max_length=200)),
                ('tag1', models.CharField(help_text='e.g., PYTHON / DJANGO', max_length=100)),
                ('tag2', models.CharField(help_text='e.g., FULL-TIME', max_length=100)),
                ('tag3', models.CharField(help_text='e.g., REMOTE', max_length=100)),
                ('description', models.TextField(help_text='Job details here...')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_role',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='prev_company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='prev_role',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='short_note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
