# Generated by Django 6.0.5 on 2026-06-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_agency', '0006_jobopening_rename_applied_role_jobapplication_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
