# Generated by Django 6.0.5 on 2026-06-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_agency', '0007_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_url', models.URLField(help_text='Instagram Reel chi link (e.g., https://www.instagram.com/reel/...)')),
                ('thumbnail', models.ImageField(help_text='Reel cha cover photo', upload_to='reels_thumbnails/')),
                ('views', models.CharField(default='10.5K', help_text='e.g., 15.2K', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
